version: "3.4"
services:
  spir-caddy:
    image: ghcr.io/fantastiskefroe/spir-caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: always

  spir-app:
    image: ghcr.io/fantastiskefroe/spir-app:latest
    restart: always

  spir-products:
    image: ghcr.io/fantastiskefroe/spir-products:latest
    environment:
      PORT: 80
      SENTRY_DSN: ${PRODUCTS_SENTRY_DSN}
    restart: always

  spir-qr:
    image: ghcr.io/fantastiskefroe/spir-qr:latest
    restart: always

  spir-overview:
    image: ghcr.io/fantastiskefroe/spir-overview:latest
    restart: always

  spir-ingest:
    depends_on:
      - postgres
    image: ghcr.io/fantastiskefroe/spir-ingest:latest
    volumes:
      - ./spir-ingest/application.override.yml:/application.yml
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-database}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      SHOPIFY_HMAC_KEY: ${SHOPIFY_HMAC_KEY:-testkey}
    restart: always

  spir-ordered-products-printer:
    image: ghcr.io/fantastiskefroe/spir-ordered-products-printer:latest
    volumes:
      - ./spir-ordered-products-printer/application.override.yml:/application.yml
      - ./spir-ordered-products-printer/private.key:/private.key
    environment:
      PRINT_SCHEDULE: ${PRINT_SCHEDULE:-*/10 * * * * *}
      ORDER_API_BASE_URI: ${ORDER_API_BASE_URI:-http://localhost:8080}
      PRINT_SERVER_HOST: ${PRINT_SERVER_HOST:-localhost}
      PRINT_SERVER_USERNAME: ${PRINT_SERVER_USERNAME:-root}
      PRINT_SERVER_PRIVATE_KEY_PATH: ${PRINT_SERVER_PRIVATE_KEY_PATH:-/private.key}
      PRINT_SERVER_PRINTER_PATH: ${PRINT_SERVER_PRINTER_PATH:-/print/}
    restart: always

  staldhiphop:
    depends_on:
      - mariadb
    image: wordpress:latest
    volumes:
      - staldhiphop_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE:-database}
      WORDPRESS_DB_USER: ${MARIADB_USER:-user}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD:-password}
      WORDPRESS_TABLE_PREFIX: ${STALDHIPHOP_WP_PREFIX:-wp_staldhiphop_}
    restart: always

  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-database}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    restart: always

  mariadb:
    image: mariadb:10.8
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-database}
      MARIADB_USER: ${MARIADB_USER:-user}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
    restart: always


volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  mariadb_data:
  staldhiphop_data:
