version: "3.4"
services:
  spir-caddy:
    image: ghcr.io/fantastiskefroe/spir-caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: always

  spir-app:
    image: ghcr.io/fantastiskefroe/spir-app:latest
    restart: always

  spir-products:
    image: ghcr.io/fantastiskefroe/spir-products:latest
    environment:
      SPIR_PRODUCTS_PORT: 80
    restart: always

  spir-qr:
    image: ghcr.io/fantastiskefroe/spir-qr:latest
    restart: always

  spir-ingest:
    depends_on:
      - postgres
    image: ghcr.io/fantastiskefroe/spir-ingest:latest
    volumes:
      - ./spir-ingest/application.override.yml:/application.yml
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-database}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      SHOPIFY_HMAC_KEY: ${SHOPIFY_HMAC_KEY:-testkey}
      
    restart: always

  spir-ordered-products-printer:
    image: ghcr.io/fantastiskefroe/spir-ordered-products-printer:latest
    volumes:
      - ./spir-ordered-products-printer/application.override.yml:/application.yml
      - ./spir-ordered-products-printer/private.key:/private.key
    
    environment:
      PRINT_SCHEDULE: ${PRINT_SCHEDULE:-*/10 * * * * *}
      ORDER_API_BASE_URI: ${ORDER_API_BASE_URI:-http://localhost:8080}
      PRINT_SERVER_HOST: ${PRINT_SERVER_HOST:-localhost}
      PRINT_SERVER_USERNAME: ${PRINT_SERVER_USERNAME:-root}
      PRINT_SERVER_PRIVATE_KEY_PATH: ${PRINT_SERVER_PRIVATE_KEY_PATH:-/private.key}
      PRINT_SERVER_PRINTER_PATH: ${PRINT_SERVER_PRINTER_PATH:-/print/}
      
    restart: always

  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-database}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    restart: always

    
volumes:
  caddy_data:
  caddy_config:
  postgres_data:
