version: "3.4"
services:
  caddy:
    image: ghcr.io/fantastiskefroe/spir-caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data

  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ${POSTGRES_DB:-database}
        POSTGRES_USER: ${POSTGRES_USER:-user}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}


volumes:
  caddy_data:
  postgres_data:
